project:
  type: website
  output-dir: docs

website:
  title: "hxyv's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hxyv
      - icon: strava
        href: https://www.strava.com/athletes/67294357
      - icon: twitter
        href: https://twitter.com/dx2033924
format:
  html:
    theme: litera
    css: styles.css

editor: visual

